# -*- coding: utf-8 -*-
"""IT A PROJECT 1

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13GTe4mfJjlL32Jr7pNjlhgT1lCfRBh_9
"""



"""# Task
Develop an intrusion detection system using the NSL-KDD dataset by downloading it from `kagglehub.dataset_download("hassan06/nslkdd")`, loading the CSV files (KDDTest+.txt, KDDTest+-21.txt, KDDTrain+.txt, KDDTrain+-21.txt), and preprocessing features. Apply K-Means clustering for unsupervised anomaly detection. Train and evaluate Decision Tree, Random Forest, and Deep Neural Network supervised models using accuracy, precision-recall curves, and confusion matrices with visualizations. Analyze and visualize feature contributions for intrusion detection, and finally, summarize all findings, model comparisons, unsupervised learning insights, and impactful features, providing recommendations.

## Download and Load Dataset

### Subtask:
Download the NSL-KDD dataset using `kagglehub.dataset_download("hassan06/nslkdd")` and load the relevant CSV files (e.g., KDDTest+.txt, KDDTest+-21.txt, KDDTrain+.txt, KDDTrain+-21.txt) into pandas DataFrames.

**Reasoning**:
The first instruction is to import the `kagglehub` library, which is necessary for downloading the dataset from Kaggle.
"""

import kagglehub
print("kagglehub library imported.")

"""**Reasoning**:
Now that `kagglehub` is imported, I will download the NSL-KDD dataset using `kagglehub.dataset_download` and store the path to the downloaded files.


"""

dataset_path = kagglehub.dataset_download("hassan06/nslkdd")
print(f"NSL-KDD dataset downloaded to: {dataset_path}")

"""**Reasoning**:
I need to import the pandas library to load the CSV files into DataFrames as per the next instruction.


"""

import pandas as pd
print("pandas library imported.")

"""**Reasoning**:
I will load the specified NSL-KDD dataset files (`KDDTest+.txt`, `KDDTest+-21.txt`, `KDDTrain+.txt`, `KDDTrain+-21.txt`) into pandas DataFrames, combining the `dataset_path` with each filename. I will also print the head of each DataFrame to verify successful loading.


"""

import os

# Define the filenames to load
filenames = [
    "KDDTest+.txt",
    "KDDTest+-21.txt",
    "KDDTrain+.txt",
    "KDDTrain+-21.txt"
]

# Dictionary to store the dataframes
dfs = {}

# Load each file into a DataFrame
for filename in filenames:
    file_path = os.path.join(dataset_path, filename)
    # Assuming the files are comma-separated. If not, this might need adjustment.
    # NSL-KDD files are often tab-separated or space-separated, but let's try common delimiters.
    # A quick search for NSL-KDD often suggests comma or space as delimiters.
    # For this dataset, they are typically comma-separated.
    try:
        df_name = filename.replace('.txt', '').replace('+', '') # Clean up name for dict key
        df = pd.read_csv(file_path, header=None)
        dfs[df_name] = df
        print(f"Successfully loaded {filename} into DataFrame '{df_name}'. Head of DataFrame:")
        print(df.head())
        print("\n")
    except Exception as e:
        print(f"Error loading {filename}: {e}")
        # If comma fails, try space as a common alternative for KDD datasets.
        try:
            df = pd.read_csv(file_path, header=None, delim_whitespace=True)
            dfs[df_name] = df
            print(f"Successfully re-loaded {filename} with space delimiter into DataFrame '{df_name}'. Head of DataFrame:")
            print(df.head())
            print("\n")
        except Exception as e_space:
            print(f"Error loading {filename} with space delimiter: {e_space}")

"""**Reasoning**:
The previous code failed because some files were not found. I will list the contents of the `dataset_path` to verify the actual filenames and then update the `filenames` list in the loading code.


"""

import os

# List all files in the downloaded dataset directory to verify names
print("Files in dataset directory:")
for f in os.listdir(dataset_path):
    print(f)

# Based on the error, it seems 'KDDTest+-21.txt' and 'KDDTrain+-21.txt' might not exist or have slightly different names.
# Let's adjust the filenames based on common NSL-KDD dataset structures and the actual files found.
# Common files are 'KDDTest+.txt' and 'KDDTrain+.txt', and sometimes 'KDDTest.txt', 'KDDTrain.txt'.
# The task explicitly mentioned 'KDDTest+-21.txt' and 'KDDTrain+-21.txt', but they were not found.
# I will proceed with the ones that are likely present based on the output and typical NSL-KDD structure.
# If the task specifically requires the '-21' version and they are not present, this needs further clarification.
# For now, I will assume the task intends to load the main test and train sets, and potentially the '20 Percent' versions if they exist as 'KDDTest_20Percent.txt' etc.

# Re-defining filenames based on typical NSL-KDD available files in many distributions,
# and assuming the original intention was to load a subset or full dataset versions.
# Given the previous error, I will stick to KDDTest+.txt and KDDTrain+.txt for now,
# and investigate if the '-21' versions are actually needed or exist with a different name.
# Upon checking typical NSL-KDD datasets, files like 'KDDTest.txt', 'KDDTrain.txt' and 'KDDTest+.txt', 'KDDTrain+.txt' are common.
# The '-21' suffix is less common for actual filenames but might refer to a specific attack type or version.

# Let's re-run the loading logic, focusing on the files that are likely to be found.
# If 'KDDTest+-21.txt' and 'KDDTrain+-21.txt' are crucial, the user needs to provide their exact names if they exist,
# or clarify if these refer to a specific subset that needs to be generated.

# For now, I'll update the filenames list to only include the ones that were successfully loaded or commonly exist.
# I'll check the directory listing to be absolutely sure.

found_files = os.listdir(dataset_path)

actual_filenames_to_load = []
if 'KDDTest+.txt' in found_files:
    actual_filenames_to_load.append('KDDTest+.txt')
if 'KDDTrain+.txt' in found_files:
    actual_filenames_to_load.append('KDDTrain+.txt')
# Check for 20% versions if they exist, which are often named like 'KDDTest_20Percent.txt'
# or if the user meant 'KDDTest+.20.txt' (not common) or similar.
# Since the original request explicitly mentioned 'KDDTest+-21.txt' and 'KDDTrain+-21.txt' and they failed to load,
# I will comment them out for now and proceed with the ones that successfully loaded.
# If the user specifically meant other files, they will need to be identified from the dataset content.

# If the task requires 'KDDTest+-21.txt' and 'KDDTrain+-21.txt' specifically, it implies those files should be present.
# The error `[Errno 2] No such file or directory` confirms they are not directly available under those names.

# Let's try to load only the files that *did* load successfully in the previous attempt and are common.
# This means 'KDDTest+.txt' and 'KDDTrain+.txt'.
# I will modify the filenames list to reflect this, and then the original loop should work.

# Redefine filenames based on what was successfully loaded and is typically present
filenames = [
    "KDDTest+.txt",
    "KDDTrain+.txt"
]

# Dictionary to store the dataframes
dfs = {}

print(f"Attempting to load the following files: {filenames}")

# Load each file into a DataFrame
for filename in filenames:
    file_path = os.path.join(dataset_path, filename)
    try:
        # NSL-KDD files often have a mix of comma and space delimiters or just spaces.
        # Trying comma first, then space as fallback.
        df_name = filename.replace('.txt', '').replace('+', '') # Clean up name for dict key
        df = pd.read_csv(file_path, header=None)
        dfs[df_name] = df
        print(f"Successfully loaded {filename} into DataFrame '{df_name}'. Head of DataFrame:")
        print(df.head())
        print("\n")
    except Exception as e:
        print(f"Error loading {filename} with comma delimiter: {e}")
        try:
            df = pd.read_csv(file_path, header=None, delim_whitespace=True)
            dfs[df_name] = df
            print(f"Successfully re-loaded {filename} with space delimiter into DataFrame '{df_name}'. Head of DataFrame:")
            print(df.head())
            print("\n")
        except Exception as e_space:
            print(f"Error loading {filename} with space delimiter: {e_space}")


print("DataFrames loaded:")
for name, df_obj in dfs.items():
    print(f"  '{name}': Shape {df_obj.shape}")

"""**Reasoning**:
The previous attempt to load `KDDTest+-21.txt` and `KDDTrain+-21.txt` failed because these exact files were not found in the downloaded dataset. The directory listing showed that `KDDTest-21.txt` exists, which is likely the intended file for `KDDTest+-21.txt` due to a minor naming difference. I will now attempt to load `KDDTest-21.txt`.


"""

import os

# Add KDDTest-21.txt to the list of files to load, as it exists in the directory
# and is likely the intended file for KDDTest+-21.txt
# Note: KDDTrain+-21.txt does not have a clear existing counterpart.
filenames_to_add = [
    "KDDTest-21.txt"
]

# Reuse the existing dfs dictionary for consistency
# Ensure the previous successful loads are still present.
# The `dfs` dict currently has KDDTest and KDDTrain from previous successful loads.
# If this is a new run, initialize it:
if 'dfs' not in locals():
    dfs = {}

print(f"Attempting to load additional files: {filenames_to_add}")

# Load each new file into a DataFrame
for filename in filenames_to_add:
    file_path = os.path.join(dataset_path, filename)
    try:
        df_name = filename.replace('.txt', '').replace('+', '') # Clean up name for dict key
        df = pd.read_csv(file_path, header=None)
        dfs[df_name] = df
        print(f"Successfully loaded {filename} into DataFrame '{df_name}'. Head of DataFrame:")
        print(df.head())
        print("\n")
    except Exception as e:
        print(f"Error loading {filename} with comma delimiter: {e}")
        try:
            df = pd.read_csv(file_path, header=None, delim_whitespace=True)
            dfs[df_name] = df
            print(f"Successfully re-loaded {filename} with space delimiter into DataFrame '{df_name}'. Head of DataFrame:")
            print(df.head())
            print("\n")
        except Exception as e_space:
            print(f"Error loading {filename} with space delimiter: {e_space}")


print("All DataFrames loaded/attempted:")
for name, df_obj in dfs.items():
    print(f"  '{name}': Shape {df_obj.shape}")

"""**Reasoning**:
I have successfully loaded 'KDDTest+.txt', 'KDDTrain+.txt', and 'KDDTest-21.txt'. The original instruction requested `KDDTrain+-21.txt`, but this file does not exist in the downloaded dataset. However, `KDDTrain+_20Percent.txt` is present and is a common subset in NSL-KDD datasets. I will attempt to load `KDDTrain+_20Percent.txt` as the likely intended file for a training subset, similar to how `KDDTest-21.txt` was used for `KDDTest+-21.txt`.


"""

import os

# Add KDDTrain+_20Percent.txt to the list of files to load
# This is a common subset in NSL-KDD and likely the intended file for 'KDDTrain+-21.txt'
filenames_to_add = [
    "KDDTrain+_20Percent.txt"
]

# The `dfs` dict currently has KDDTest, KDDTrain, and KDDTest-21 from previous successful loads.
# Ensure it exists and is populated for this run.
if 'dfs' not in locals():
    dfs = {}

print(f"Attempting to load additional files: {filenames_to_add}")

# Load each new file into a DataFrame
for filename in filenames_to_add:
    file_path = os.path.join(dataset_path, filename)
    try:
        # Clean up name for dict key, e.g., 'KDDTrain_20Percent'
        df_name = filename.replace('.txt', '').replace('+', '').replace('_', '')
        df = pd.read_csv(file_path, header=None)
        dfs[df_name] = df
        print(f"Successfully loaded {filename} into DataFrame '{df_name}'. Head of DataFrame:")
        print(df.head())
        print("\n")
    except Exception as e:
        print(f"Error loading {filename} with comma delimiter: {e}")
        try:
            df = pd.read_csv(file_path, header=None, delim_whitespace=True)
            dfs[df_name] = df
            print(f"Successfully re-loaded {filename} with space delimiter into DataFrame '{df_name}'. Head of DataFrame:")
            print(df.head())
            print("\n")
        except Exception as e_space:
            print(f"Error loading {filename} with space delimiter: {e_space}")


print("All DataFrames loaded/attempted:")
for name, df_obj in dfs.items():
    print(f"  '{name}': Shape {df_obj.shape}")

"""## Preprocess Features

### Subtask:
Preprocess both categorical and numerical features. This includes encoding categorical features using techniques like One-Hot Encoding and scaling numerical features (e.g., StandardScaler or MinMaxScaler). Also, handle any missing values or inconsistencies in the dataset.

**Reasoning**:
The first step is to define the column names for the NSL-KDD dataset. This is crucial as the dataframes were loaded without headers, and having descriptive column names will facilitate subsequent preprocessing steps like identifying categorical and numerical features and creating the binary target variable.
"""

columns = [
    'duration', 'protocol_type', 'service', 'flag', 'src_bytes', 'dst_bytes',
    'land', 'wrong_fragment', 'urgent', 'hot', 'num_failed_logins', 'logged_in',
    'num_compromised', 'root_shell', 'su_attempted', 'num_root', 'num_file_creations',
    'num_shells', 'num_access_files', 'num_outbound_cmds', 'is_host_login',
    'is_guest_login', 'count', 'srv_count', 'serror_rate', 'srv_serror_rate',
    'rerror_rate', 'srv_rerror_rate', 'same_srv_rate', 'diff_srv_rate',
    'srv_diff_host_rate', 'dst_host_count', 'dst_host_srv_count',
    'dst_host_same_srv_rate', 'dst_host_diff_srv_rate',
    'dst_host_same_src_port_rate', 'dst_host_srv_diff_host_rate', 'dst_host_serror_rate',
    'dst_host_srv_serror_rate', 'dst_host_rerror_rate', 'dst_host_srv_rerror_rate',
    'attack_type', 'difficulty_score'
]

for df_name, df_obj in dfs.items():
    df_obj.columns = columns
    print(f"Columns set for DataFrame '{df_name}'. Head of DataFrame with columns:")
    print(df_obj.head())
    print("\n")

"""**Reasoning**:
Now that the column names are set, I will convert the `attack_type` column into a binary target variable for each DataFrame. 'normal' will be mapped to 0, and all other attack types will be mapped to 1. This is a crucial step for preparing the data for supervised learning models.


"""

for df_name, df_obj in dfs.items():
    # Create a new binary target column
    df_obj['binary_attack'] = df_obj['attack_type'].apply(lambda x: 0 if x == 'normal' else 1)
    print(f"Binary attack type distribution for DataFrame '{df_name}':")
    print(df_obj['binary_attack'].value_counts())
    print("\n")

"""**Reasoning**:
I will identify categorical and numerical feature columns from the DataFrames, excluding the `attack_type`, `difficulty_score`, and the newly created `binary_attack` columns, which are target variables.


"""

import numpy as np

# Define the target columns to be excluded from feature processing
target_cols = ['attack_type', 'difficulty_score', 'binary_attack']

# Identify categorical and numerical features from the columns list
# We can infer these based on common NSL-KDD dataset structure and previous column definition
# 'protocol_type', 'service', 'flag' are typically categorical.

categorical_features = ['protocol_type', 'service', 'flag']

# All other columns, excluding target_cols and categorical_features, are numerical
numerical_features = [col for col in columns if col not in categorical_features and col not in target_cols]

print(f"Identified Categorical Features: {categorical_features}")
print(f"Identified Numerical Features: {numerical_features}")

# Also, let's create a dictionary to store the preprocessed feature sets and target variables
X_data = {}
y_data = {}

for df_name, df_obj in dfs.items():
    X_data[df_name] = df_obj.drop(columns=target_cols)
    y_data[df_name] = df_obj['binary_attack']
    print(f"\nPrepared features (X) shape for '{df_name}': {X_data[df_name].shape}")
    print(f"Prepared target (y) shape for '{df_name}': {y_data[df_name].shape}")

"""**Reasoning**:
I will apply One-Hot Encoding to the categorical features across all DataFrames. To ensure consistent encoding (i.e., that all possible categories are included even if they don't appear in a single split), I will first concatenate all feature DataFrames, apply `pd.get_dummies()` to the identified categorical columns, and then split them back into their original training and testing sets. This ensures that the same columns are generated for all datasets.


"""

import pandas as pd

# Create a combined DataFrame of all X_data for consistent One-Hot Encoding
combined_X = pd.concat(X_data.values(), keys=X_data.keys())

print(f"Combined X shape before One-Hot Encoding: {combined_X.shape}")

# Apply One-Hot Encoding to categorical features
combined_X_encoded = pd.get_dummies(combined_X, columns=categorical_features, drop_first=False)

print(f"Combined X shape after One-Hot Encoding: {combined_X_encoded.shape}")

# Split the combined, encoded DataFrame back into individual DataFrames
encoded_X_data = {}
start_idx = 0
for df_name, original_df in X_data.items():
    end_idx = start_idx + original_df.shape[0]
    encoded_X_data[df_name] = combined_X_encoded.iloc[start_idx:end_idx]
    start_idx = end_idx

# Update X_data with the encoded dataframes
X_data = encoded_X_data

# Verify the shapes and a sample of the encoded data
for df_name, df_obj in X_data.items():
    print(f"\nEncoded features (X) shape for '{df_name}': {df_obj.shape}")
    if df_name == 'KDDTrain': # Only print head for KDDTrain as an example
        print(f"Head of encoded features for '{df_name}':")
        print(df_obj.head())

"""**Reasoning**:
I will initialize a `StandardScaler` and apply it to the numerical features of all DataFrames. To avoid data leakage, I will fit the scaler only on the numerical features of the main training DataFrame (`KDDTrain`) and then transform the numerical features across all DataFrames (`KDDTest`, `KDDTest-21`, `KDDTrain`, `KDDTrain20Percent`).


"""

from sklearn.preprocessing import StandardScaler

# Initialize the StandardScaler
scaler = StandardScaler()

# Create a dictionary to store the scaled numerical features
scaled_numerical_features = {}

# Fit the scaler on the numerical features of the training DataFrame (KDDTrain)
# and then transform all DataFrames
print(f"Fitting StandardScaler on numerical features of 'KDDTrain'...")
# Ensure the numerical features are selected from X_data['KDDTrain']
scaler.fit(X_data['KDDTrain'][numerical_features])
print("Scaler fitted successfully.")

for df_name, df_obj in X_data.items():
    # Transform the numerical features of the current DataFrame
    scaled_data = scaler.transform(df_obj[numerical_features])

    # Create a DataFrame from the scaled data with original numerical feature names
    scaled_numerical_df = pd.DataFrame(scaled_data, columns=numerical_features, index=df_obj.index)

    # Store the scaled numerical features
    scaled_numerical_features[df_name] = scaled_numerical_df

    print(f"Numerical features in '{df_name}' scaled. Shape: {scaled_numerical_df.shape}")
    if df_name == 'KDDTrain':
        print(f"Head of scaled numerical features for '{df_name}':")
        print(scaled_numerical_df.head())

"""**Reasoning**:
Now that both categorical and numerical features have been processed (one-hot encoded and scaled, respectively), I will concatenate these processed features for each DataFrame to form the final preprocessed feature sets. This will result in `X_train`, `X_test`, `X_train_20Percent`, and `X_test_21` as specified in the instructions. I will then display their shapes and the head of `X_train` to verify the transformation.


"""

X_processed = {}

for df_name in X_data.keys():
    # Select numerical features from the one-hot encoded dataframe
    # and categorical features (which are already one-hot encoded in X_data)

    # The X_data already contains all features, with categorical ones one-hot encoded.
    # The scaled_numerical_features contains only the numerical ones, scaled.
    # So, we need to replace the original numerical columns in X_data[df_name]
    # with their scaled versions, then ensure column order/completeness.

    # Create a copy of the encoded_X_data to modify
    temp_df = X_data[df_name].copy()

    # Replace the numerical columns with their scaled versions
    for col in numerical_features:
        temp_df[col] = scaled_numerical_features[df_name][col]

    X_processed[df_name] = temp_df

# Rename keys for clarity as per instruction: X_train, X_test, X_train_20Percent, X_test_21
# Assuming KDDTrain is X_train, KDDTest is X_test, KDDTest-21 is X_test_21, KDDTrain20Percent is X_train_20Percent
final_X = {
    'X_train': X_processed['KDDTrain'],
    'X_test': X_processed['KDDTest'],
    'X_test_21': X_processed['KDDTest-21'],
    'X_train_20Percent': X_processed['KDDTrain20Percent']
}

final_y = {
    'y_train': y_data['KDDTrain'],
    'y_test': y_data['KDDTest'],
    'y_test_21': y_data['KDDTest-21'],
    'y_train_20Percent': y_data['KDDTrain20Percent']
}

print("Final Preprocessed Feature Sets and Target Variables:")
for name, df_obj in final_X.items():
    print(f"  '{name}' shape: {df_obj.shape}")
for name, series_obj in final_y.items():
    print(f"  '{name}' shape: {series_obj.shape}")

print(f"\nHead of X_train:")
print(final_X['X_train'].head())

"""## Apply Unsupervised Learning (K-Means)

### Subtask:
Apply K-Means clustering for unsupervised anomaly detection. This involves training the K-Means model on the appropriate features and identifying clusters that represent anomalies, potentially comparing results between normal and abnormal clusters.

**Reasoning**:
I will import the `KMeans` class, initialize the model with `n_clusters=2`, fit it to the training data, predict cluster labels for both training and test sets, and then analyze the distribution of actual binary attack labels within the K-Means clusters using `pd.crosstab`, finally printing the model's inertia.
"""

from sklearn.cluster import KMeans
import pandas as pd

# 2. Initialize a KMeans model
kmeans = KMeans(n_clusters=2, random_state=42, n_init='auto')
print("KMeans model initialized.")

# 3. Fit the KMeans model to the preprocessed training features
kmeans.fit(final_X['X_train'])
print("KMeans model fitted to X_train.")

# 4. Predict the cluster labels for both the training and test set
kmeans_train_labels = kmeans.predict(final_X['X_train'])
kmeans_test_labels = kmeans.predict(final_X['X_test'])
print("Cluster labels predicted for training and test sets.")

# 5. Analyze the distribution of actual binary attack labels within each cluster
print("\nDistribution of actual binary attack labels within KMeans clusters (Training Set):")
cluster_distribution = pd.crosstab(kmeans_train_labels, final_y['y_train'])
cluster_distribution.index.name = 'KMeans Cluster'
cluster_distribution.columns = ['Normal (0)', 'Anomaly (1)']
print(cluster_distribution)

# 6. Print the KMeans model's inertia_
print(f"\nKMeans model inertia: {kmeans.inertia_}")

"""## Train Supervised Models

### Subtask:
Train the specified supervised machine learning models: Decision Tree, Random Forest, and a Deep Neural Network. This will involve splitting the preprocessed data into training and testing sets and training each model on the training data.

**Reasoning**:
I will import the necessary classifier classes for Decision Tree, Random Forest, and MLPClassifier (Deep Neural Network) from scikit-learn, then initialize and train each model using the preprocessed training data (`final_X['X_train']` and `final_y['y_train']`).
"""

from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.neural_network import MLPClassifier

print("Classifier libraries imported.")

# Initialize and train Decision Tree model
dt_model = DecisionTreeClassifier(random_state=42)
dt_model.fit(final_X['X_train'], final_y['y_train'])
print("Decision Tree model trained successfully.")

# Initialize and train Random Forest model
rf_model = RandomForestClassifier(random_state=42)
rf_model.fit(final_X['X_train'], final_y['y_train'])
print("Random Forest model trained successfully.")

# Initialize and train Deep Neural Network (MLPClassifier) model
dnn_model = MLPClassifier(hidden_layer_sizes=(100, 50), max_iter=200, random_state=42)
dnn_model.fit(final_X['X_train'], final_y['y_train'])
print("Deep Neural Network model trained successfully.")

"""## Evaluate Supervised Models

### Subtask:
Evaluate the performance of each supervised model using Accuracy, Precision-Recall curves, and Confusion Matrices. Provide visualizations for the Confusion Matrices with appropriate legends to clearly show true positives, true negatives, false positives, and false negatives.

**Reasoning**:
I will import the necessary metrics and plotting functions for evaluation, including `accuracy_score`, `confusion_matrix`, `precision_recall_curve`, `auc`, `matplotlib.pyplot`, and `ConfusionMatrixDisplay`. This is the first step to enable model evaluation and visualization as specified in the instructions.
"""

from sklearn.metrics import accuracy_score, confusion_matrix, precision_recall_curve, auc, ConfusionMatrixDisplay
import matplotlib.pyplot as plt
import numpy as np

print("Evaluation metrics and plotting libraries imported.")

"""**Reasoning**:
I will define two helper functions: `plot_confusion_matrix` to visualize confusion matrices with clear labels for true positives, true negatives, false positives, and false negatives, and `plot_precision_recall_curve` to generate precision-recall curves for model evaluation. These functions will be used to evaluate the performance of the trained supervised models.


"""

def plot_confusion_matrix(y_true, y_pred, title):
    cm = confusion_matrix(y_true, y_pred)

    # Define class labels for the plot
    class_names = ['Normal (0)', 'Anomaly (1)']

    disp = ConfusionMatrixDisplay(confusion_matrix=cm, display_labels=class_names)
    fig, ax = plt.subplots(figsize=(6, 6))
    disp.plot(cmap=plt.cm.Blues, ax=ax)
    ax.set_title(title)

    # Add labels for TP, TN, FP, FN
    tn, fp, fn, tp = cm.ravel()
    ax.text(0.75, 0.25, f'TP: {tp}', color='white', ha='center', va='center', fontsize=12)
    ax.text(0.75, 0.75, f'FN: {fn}', color='black', ha='center', va='center', fontsize=12)
    ax.text(0.25, 0.25, f'FP: {fp}', color='black', ha='center', va='center', fontsize=12)
    ax.text(0.25, 0.75, f'TN: {tn}', color='white', ha='center', va='center', fontsize=12)

    plt.show()

def plot_precision_recall_curve(y_true, y_scores, title):
    precision, recall, _ = precision_recall_curve(y_true, y_scores)
    pr_auc = auc(recall, precision)

    plt.figure(figsize=(8, 6))
    plt.plot(recall, precision, label=f'Precision-Recall curve (AUC = {pr_auc:.2f})')
    plt.xlabel('Recall')
    plt.ylabel('Precision')
    plt.title(f'Precision-Recall Curve: {title}')
    plt.legend(loc='lower left')
    plt.grid(True)
    plt.show()

print("Helper functions 'plot_confusion_matrix' and 'plot_precision_recall_curve' defined.")

"""**Reasoning**:
Now that the helper functions are defined, I will evaluate each of the trained supervised models (Decision Tree, Random Forest, and Deep Neural Network) by predicting on the test set (`final_X['X_test']`), calculating and printing the accuracy, and then generating a confusion matrix and a precision-recall curve visualization for each model using the previously defined helper functions.


"""

models = {
    "Decision Tree": dt_model,
    "Random Forest": rf_model,
    "Deep Neural Network": dnn_model
}

for name, model in models.items():
    print(f"\n--- Evaluating {name} Model ---")

    # a. Predict the binary attack labels
    y_pred = model.predict(final_X['X_test'])

    # b. Calculate the accuracy score
    accuracy = accuracy_score(final_y['y_test'], y_pred)
    # c. Print the accuracy score
    print(f"Accuracy for {name}: {accuracy:.4f}")

    # d. Call the plot_confusion_matrix helper function
    plot_confusion_matrix(final_y['y_test'], y_pred, title=f'{name} Confusion Matrix')

    # e. Predict the probability scores for the positive class
    y_scores = model.predict_proba(final_X['X_test'])[:, 1]

    # f. Call the plot_precision_recall_curve helper function
    plot_precision_recall_curve(final_y['y_test'], y_scores, title=f'{name} Precision-Recall Curve')

"""## Analyze Feature Contributions

### Subtask:
Analyze which features contribute most to detecting intrusions. This can be done by examining feature importance scores from tree-based models like Decision Tree or Random Forest, and visualizing the top contributing features in a bar chart with legends.

**Reasoning**:
I will extract the feature importance scores from the trained `Decision Tree` and `Random Forest` models. Then, I will create a Pandas Series for each model's feature importances, using the column names from `final_X['X_train']` as the index. This will prepare the data for identifying and visualizing the top contributing features as specified in the instructions.
"""

import pandas as pd

# 1. Extract feature importance scores from the trained Decision Tree model (dt_model)
dt_feature_importances = pd.Series(dt_model.feature_importances_, index=final_X['X_train'].columns)

# 2. Extract feature importance scores from the trained Random Forest model (rf_model)
rf_feature_importances = pd.Series(rf_model.feature_importances_, index=final_X['X_train'].columns)

print("Feature importances extracted for Decision Tree and Random Forest models.")

print("\nDecision Tree Feature Importances (Top 5):")
print(dt_feature_importances.nlargest(5))

print("\nRandom Forest Feature Importances (Top 5):")
print(rf_feature_importances.nlargest(5))

"""**Reasoning**:
Now that the feature importances for both Decision Tree and Random Forest models have been extracted, I will identify the top 10 most important features for each model and create horizontal bar charts to visualize them. This will allow for a clear comparison of feature contributions between the two models.


"""

import matplotlib.pyplot as plt

# Get top 10 features for Decision Tree
dt_top_10_features = dt_feature_importances.nlargest(10)

# Get top 10 features for Random Forest
rf_top_10_features = rf_feature_importances.nlargest(10)

# Plotting Decision Tree Top 10 Feature Importances
plt.figure(figsize=(12, 7))
dt_top_10_features.sort_values(ascending=True).plot(kind='barh', color='skyblue')
plt.title('Decision Tree: Top 10 Feature Importances for Intrusion Detection')
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

# Plotting Random Forest Top 10 Feature Importances
plt.figure(figsize=(12, 7))
rf_top_10_features.sort_values(ascending=True).plot(kind='barh', color='lightcoral')
plt.title('Random Forest: Top 10 Feature Importances for Intrusion Detection')
plt.xlabel('Feature Importance Score')
plt.ylabel('Features')
plt.tight_layout()
plt.show()

print("Top 10 feature importances for Decision Tree and Random Forest visualized.")

model_results = {}

for name, model in models.items():
    print(f"\n--- Collecting Metrics for {name} Model ---")

    # Predict the binary attack labels
    y_pred = model.predict(final_X['X_test'])

    # Calculate Accuracy
    accuracy = accuracy_score(final_y['y_test'], y_pred)

    # Calculate Confusion Matrix metrics
    cm = confusion_matrix(final_y['y_test'], y_pred)
    tn, fp, fn, tp = cm.ravel()

    # Predict the probability scores for the positive class for PR AUC
    y_scores = model.predict_proba(final_X['X_test'])[:, 1]
    precision, recall, _ = precision_recall_curve(final_y['y_test'], y_scores)
    pr_auc = auc(recall, precision)

    model_results[name] = {
        'Accuracy': accuracy,
        'Precision-Recall AUC': pr_auc,
        'True Positives (TP)': tp,
        'True Negatives (TN)': tn,
        'False Positives (FP)': fp,
        'False Negatives (FN)': fn
    }

    print(f"  Accuracy: {accuracy:.4f}")
    print(f"  Precision-Recall AUC: {pr_auc:.4f}")
    print(f"  TP: {tp}, TN: {tn}, FP: {fp}, FN: {fn}")

# Display the results in a DataFrame for a clear comparison table
results_df = pd.DataFrame(model_results).T
print("\nElaborate Model Comparison Table:")
display(results_df)

"""## Final Task

### Subtask:
Summarize the findings, including the performance comparison of different supervised models, the insights from unsupervised learning, and the most impactful features for intrusion detection based on the analysis. Provide recommendations or conclusions based on the overall results.

## Summary:

### Q&A
The analysis successfully addresses the task's summarization requirements:

*   **Performance comparison of different supervised models:** The Deep Neural Network achieved the highest accuracy (0.7879), closely followed by the Decision Tree (0.7854), and then the Random Forest model (0.7648) on the test set. All models demonstrated reasonable performance in distinguishing between normal and anomalous network traffic.
*   **Insights from unsupervised learning:** K-Means clustering, with \$n\_clusters=2\$, largely separated normal and anomalous traffic. Cluster 1 contained 44,566 anomalies and 168 normal samples, strongly indicating anomalous activity. Cluster 0 was predominantly normal (67,175 samples) but also contained a significant number of anomalies (14,064 samples), suggesting some overlap or misclassification by K-Means.
*   **Most impactful features for intrusion detection:**
    *   **Decision Tree:** `src_bytes` was overwhelmingly the most important feature (0.739), followed by `service_ecr_i` (0.075) and `service_http` (0.056).
    *   **Random Forest:** `src_bytes` remained the most important (0.169), but its dominance was less pronounced. Other significant features included `dst_bytes` (0.083), `flag_SF` (0.068), `dst_host_same_srv_rate` (0.057), and `dst_host_srv_count` (0.057).
*   **Recommendations or conclusions:** The supervised models show strong potential for intrusion detection, with DNN slightly outperforming others. The unsupervised K-Means provided a useful initial separation of data, although it showed some limitations in perfectly isolating anomalies. Feature importance analysis highlights the critical role of network traffic volume (`src_bytes`, `dst_bytes`) and specific service/flag types in detecting intrusions.

### Data Analysis Key Findings
*   **Dataset Loading and Preparation:** The NSL-KDD dataset was successfully downloaded. Four dataframes were loaded: `KDDTest` (shape: 22544, 43), `KDDTrain` (shape: 125973, 43), `KDDTest-21` (shape: 11850, 43), and `KDDTrain20Percent` (shape: 25192, 43). Initial discrepancies in specific filenames were resolved by identifying their existing counterparts.
*   **Feature Preprocessing:**
    *   Standard NSL-KDD column names were assigned.
    *   A binary target variable `binary_attack` was created, mapping 'normal' to 0 and all other attack types to 1.
    *   Categorical features (`protocol_type`, `service`, `flag`) were One-Hot Encoded, expanding the feature set from 41 to 122 columns.
    *   Numerical features were scaled using `StandardScaler`, fitted on the main training set (`KDDTrain`) to prevent data leakage.
*   **Unsupervised Anomaly Detection (K-Means):**
    *   A K-Means model (\$$n\_clusters=2\$) was trained and applied.
    *   Cluster 1 showed a strong correlation with anomalies, containing 44,566 anomalous samples and only 168 normal samples in the training set.
    *   Cluster 0 was primarily normal (67,175 samples) but also included 14,064 anomalous samples, indicating some mixed cluster formation.
*   **Supervised Model Performance:**
    *   **Deep Neural Network (DNN):** Achieved the highest accuracy of 0.7879 on the test set.
    *   **Decision Tree:** Achieved an accuracy of 0.7854 on the test set.
    *   **Random Forest:** Achieved an accuracy of 0.7648 on the test set.
    *   Precision-Recall curves and Confusion Matrices were generated for all models, providing further insights into their performance, including True Positives, True Negatives, False Positives, and False Negatives.
*   **Feature Contributions:**
    *   **Decision Tree:** Identified `src_bytes` as the most critical feature with an importance score of 0.739, followed by `service_ecr_i` (0.075) and `service_http` (0.056).
    *   **Random Forest:** Also found `src_bytes` to be the most important (0.169), but distributed importance more broadly, with `dst_bytes` (0.083), `flag_SF` (0.068), `dst_host_same_srv_rate` (0.057), and `dst_host_srv_count` (0.057) also being highly influential.

### Insights or Next Steps
*   Further hyperparameter tuning for the Deep Neural Network and Random Forest models could potentially improve their accuracy and precision-recall performance.
*   Explore ensemble methods that combine the strengths of Decision Trees (clear, interpretable rules for highly impactful features) and Random Forests (robustness and better generalization) for potentially superior intrusion detection.
"""